### ISSUE TITLE
CentOS 7 does not have systemd-sysusers

### ISSUE THREAD

**Issue by MarkMendell** [caddyserver/dist#103]
On CentOS 7, I was unable to update from 2.7.4 to 2.7.5.
```
/var/tmp/rpm-tmp.joZmkn: line 1: fg: no job control
error: %pre(caddy-2.7.5-1.el7.x86_64) scriptlet failed, exit status 1
Error in PREIN scriptlet in rpm package caddy-2.7.5-1.el7.x86_64
```
I believe it is due to this commit: https://github.com/caddyserver/dist/commit/cc5eb55d5fa01986d7d161cc7067e064e3a4abd9

Specifically, this line:
https://github.com/caddyserver/dist/blob/cc5eb55d5fa01986d7d161cc7067e064e3a4abd9/rpm/caddy.spec#L109

`%sysusers_create_package` is not defined in my `/usr/lib/rpm/macros.d/macros.systemd` file, and `systemd-sysusers` (which the macro would call) is not present.

I think the answer is either to add a fallback for CentOS 7, or for CentOS 7 users to get `systemd-sysusers` and `%sysusers_create_package` (I could not figure out how to get `systemd-sysusers` on my system), or to remove the package for CentOS 7.

**Comment by francislavoie** [comment]
FYI @Conan-Kudo

**Comment by Conan-Kudo** [comment]
So, I think I've fixed it with https://github.com/caddyserver/dist/commit/0bab9492e9f6518e72738d1a362d42943da3ae68, and have wiped the build and triggered a new one that will work: https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/build/6521560/

**Comment by MarkMendell** [comment]
Thanks! It looks like I'm still getting an error. I tried both `yum update`, as well as `wget https://download.copr.fedorainfracloud.org/results/@caddy/caddy/epel-7-x86_64/06521560-caddy/caddy-2.7.5-1.el7.x86_64.rpm && yum localinstall caddy-2.7.5-1.el7.x86_64.rpm`

It's the same error, so I assume `%sysusers_create_compat` is not expanding.

**Comment by Conan-Kudo** [comment]
Here we go again with https://github.com/caddyserver/dist/commit/ef9839cce5effcb74575a77d7c9b99bac98fd3b3 and https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/build/6521573/

**Comment by MarkMendell** [comment]
That worked, thanks!
